export const SUPABASE_URL = "YOUR_SUPABASE_URL"
export const SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"
export const STRAVA_CLIENT_ID = "YOUR_STRAVA_CLIENT_ID"
export const GOOGLE_HEALTH_CLIENT_ID = "YOUR_GOOGLE_HEALTH_CLIENT_ID"
